name: Actionlint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run actionlint
        uses: rhysd/actionlint-action@486e9cd4ae9876778f654b9d08e5033734eb60e1 # v1.7.7
