name: Publish Controller to GHCR

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-controller-ghcr:
    runs-on: ubuntu-latest
    if: github.repository == 'gke-labs/kube-agents'
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Downcase repository name
        env:
          GITHUB_REPO: ${{ github.repository }}
        run: |
          echo "IMAGE_REPOSITORY=$(echo "$GITHUB_REPO" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Controller Image
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.2
        id: build-controller
        with:
          context: k8s-operator
          file: k8s-operator/Dockerfile
          push: true
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ env.IMAGE_REPOSITORY }}/k8s-operator:latest
            ghcr.io/${{ env.IMAGE_REPOSITORY }}/k8s-operator:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bec8e6aeda8f45a666c24246 # v3.8.0

      - name: Sign the image
        env:
          CONTROLLER_DIGEST: ${{ steps.build-controller.outputs.digest }}
        run: |
          cosign sign --yes "ghcr.io/${IMAGE_REPOSITORY}/k8s-operator@${CONTROLLER_DIGEST}"
