name: Prettier Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: "20"

      - name: Install Prettier
        run: npm install prettier

      - name: Run Prettier Check on changed files
        run: |
          git fetch origin ${{ github.base_ref }}
          mapfile -t CHANGED_FILES < <(git diff --name-only --diff-filter=d origin/${{ github.base_ref }}...HEAD | grep -E '\.md$|\.yaml$|\.yml$' || true)
          if [ "${#CHANGED_FILES[@]}" -gt 0 ]; then
            printf 'Checking files:\n'
            printf '%s\n' "${CHANGED_FILES[@]}"
            npx prettier --check "${CHANGED_FILES[@]}"
          else
            echo "No markdown or YAML files changed."
          fi
